### ISSUE TITLE
Missing [elasticsearch] extra

### ISSUE THREAD

**Issue by falcorocks** [testcontainers/testcontainers-python#111]
I see `testcontainers/elasticsearch.py` but 

```
root@7d069e7f01e3:/# pip install 'testcontainers[elasticsearch]'
Collecting testcontainers[elasticsearch]
  Downloading testcontainers-3.0.3.tar.gz (13 kB)
  WARNING: testcontainers 3.0.3 does not provide the extra 'elasticsearch'
(...)
```

Can you help me understand if elasticsearch is supported or not?

**Comment by tillahoffmann** [comment]
The `ElasticSearchContainer` does not require any additional dependencies at the moment and should work out of the box without installing any extras. Let me know if that's not the case.
