### ISSUE TITLE
How to create a Kafka test Container

### ISSUE THREAD

**Issue by wuqunfei** [testcontainers/testcontainers-python#121]
Could we create a Kafka container like this 
`with TestContainer(image="confluentinc/cp-kafka:5.4.3") as container:
    ip = container.get_container_host_ip()`

but I don't know how to implement a method like https://www.testcontainers.org/modules/kafka/
`kafka.getBootstrapServers()`

**Comment by ash1425** [comment]
Kafka container from confluent needs some more configurations before it can be started. I am working on a PR for kafka container. Meanwhile you can look at sample implementation at https://github.com/SrinivasanTarget/python_flask_app/blob/main/test/kafka.py

**Comment by manojhans** [comment]
@wuqunfei you can create kafka container using `DockerCompose` with specific port, here is the example: https://github.com/manojhans/python_testcontainers_kafka
