### ISSUE TITLE
Unable to provide a custom URL for selenium standalone image

### ISSUE THREAD

**Issue by shikhar08** [testcontainers/testcontainers-python#122]
Hi, 

I was attempting to subclass [`testcontainers.selenium.BrowserWebDriverContainer`]( https://github.com/testcontainers/testcontainers-python/blob/70055bc73f2b02d3d9a36e89808cf5c8a729adbf/testcontainers/selenium.py#L33) and ran into an issue. 

```python
def __init__(self, capabilities, image=None):
        self.capabilities = capabilities
        if not image:
            self.image = get_image_name(capabilities)
        self.port_to_expose = 4444
        self.vnc_port_to_expose = 5900
        super(BrowserWebDriverContainer, self).__init__(image=self.image)
        self.with_exposed_ports(self.port_to_expose, self.vnc_port_to_expose)
```

This `__init__`  does not account for when a user specifies the input `image` . As shown above, there needs to be an else statement for `image` so that we don't hit a `NameError` because `self.image` does not get declared if the user provides a custom URL for the image.

I am using an image from my company's Docker registry as I cannot download outside images. 

I'd like to submit a PR that can solve this.
The change I'd make is 

```python
def __init__(self, capabilities, image=None):
        self.capabilities = capabilities
        if  image is None:
            self.image = get_image_name(capabilities)
        else:
            self.image = image
        self.port_to_expose = 4444
        self.vnc_port_to_expose = 5900
        super(BrowserWebDriverContainer, self).__init__(image=self.image)
        self.with_exposed_ports(self.port_to_expose, self.vnc_port_to_expose)
```

For reference see [`testcontainers.redis.RedisContainer`](https://github.com/testcontainers/testcontainers-python/blob/70055bc73f2b02d3d9a36e89808cf5c8a729adbf/testcontainers/redis.py#L21); in particular: `        super(RedisContainer, self).__init__(image)` where a user-supplied `image` will be passed to the underlying class `DockerContainer`.

**Comment by tillahoffmann** [comment]
Hi @shikhar08, this sounds like a good idea. You could even simplify to
```python
self.image = image or get_image(capabilities)
```

Looking forward to the PR.

**Comment by shikhar08** [comment]
@tillahoffmann Hey that sounds like a good idea. I have used it.
