### ISSUE TITLE
PostgresContainer timeout when sqlalchemy not installed

### ISSUE THREAD

**Issue by parisni** [testcontainers/testcontainers-python#137]
Hello

For some reasons, PostgresContainer does not work when sqlalchemy is not installed.

Took me hours to figure out this.

Anyway, Thanks for this great package

**Comment by vryazanov** [comment]
Hello,
it uses sqlalchemy to check if db is up and ready 
https://github.com/testcontainers/testcontainers-python/blob/master/testcontainers/core/generic.py#L24
the right way to install lib - `pip install testcontainers[postgresql]`
