### ISSUE TITLE
Allow to specify dialect/driver when calling get_connection_url

### ISSUE THREAD

**Issue by inikolaev** [testcontainers/testcontainers-python#140]
With latest SQLAlchemy 1.4 rolling out support for asyncio it would be great to support that in some way.

In order to use asyncio one needs to use a corresponding driver which is specified in the connection string, e.g.:

```
postgresql+asyncpg://scott:tiger@localhost/test
```

But in `PostgresContainer` it's currently hardcoded to:

```
postgresql+psycopg2
```

Don't know what the best solution could be:

* Pass it as a constructor argument - but in this case there would be a limitation that `get_connection_url` will return fixed connection string, which this might not be a huge issue realistically, but feels odd, since container doesn't really care how we want to connect to it
* Pass an argument to `get_connection_url`, but this messes up with an API provided by `DbContainer` and then other implementation should probably support this as well or at least ignore unknown parameters.

**Comment by orsolli** [comment]
This is solved

**Comment by tillahoffmann** [comment]
#156 for reference.
