### ISSUE TITLE
Let selenium container have host network mode

### ISSUE THREAD

**Issue by parisni** [testcontainers/testcontainers-python#143]
So far, the selenium driver cannot access localhost based website since it is running inside it's docker container network.

One have to provide the host IP in order to give it access to local website, local api, and so on.

It would ease setup to provide an option to make the `BrowserWebDriverContainer` have host network.

**Comment by timbmg** [comment]
That should work already. The `BrowserWebDriverContainer` passes a `kwargs` object down to the `DockerContainer` constructor. When we call the `start` function,[ that kwargs object is passed to `container.run`](https://github.com/testcontainers/testcontainers-python/blob/df0c28afef8dc26c0a685b0919d9b9aa65ccc5c2/testcontainers/core/container.py#L53-L61).  And [according to the docker-py documentation](https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.run) you can pass network as a parameter. So just pass `network="host"` to the `BrowserWebDriverContainer` construtor, or any instance of `DockerContainer` for that matter.

```python3
from selenium.webdriver import DesiredCapabilities

from testcontainers.selenium import BrowserWebDriverContainer

BrowserWebDriverContainer(capabilities=DesiredCapabilities.CHROME, network="host")
```

**Comment by tillahoffmann** [comment]
Closing this for now. Feel free to get in touch if the issue persists. Thanks for the insights, @timbmg.
