### ISSUE TITLE
3.4.1 fix breaks AzureDevops container (linux) runs for postgres containers

### ISSUE THREAD

**Issue by mxab** [testcontainers/testcontainers-python#147]
Hi,

our builds stopped working when we updated to 3.4.1 since the connection url uses `localhost` instead of the ip address I get a timeout when it trys to connect to the postgres
Before the connection was something like `postgresql+psycopg2://test:***@<ip-address>:49326/test`

**Comment by mxab** [comment]
I guess this is related to #145

**Comment by sebastian-hatala-leanix** [comment]
Ha you are right - in that way this is not "only" a MacOS thing but anywhere when not running Docker under `localhost` 👍

**Comment by fjahoda** [comment]
I think this as well. https://github.com/testcontainers/testcontainers-python/commit/1a143b0bef3732c8d13f462672da4045356c0861#r52447265

Can the commit be reverted?

**Comment by sebastian-hatala-leanix** [comment]
Jup...but the commit itself probably still is a senseful addition in order to have the parameter `get_connection_url`. But the combination of having a default param as `localhost` and not passing in an argument from `DbContainer._connect` makes it bad for us

**Comment by tillahoffmann** [comment]
Apologies for the slow followup. This should now be fixed in 3.4.2 thanks to @sebastian-hatala-leanix's fix in #145.
