### ISSUE TITLE
Allow other environment variables to be set on the LocalStack Container

### ISSUE THREAD

**Issue by hrmstockdale** [testcontainers/testcontainers-python#150]
Presently the LocalStackContainer class exposes a `with_services` method to allow consumers to restrict which localstack services are run. This works by setting the `SERVICES` environment variable before running the localstack container.

The [localstack documentation](https://github.com/localstack/localstack#configurations) allows for a number of environmental variables to be set. It would be useful to be able to set others, for example being able to adjust the`DEBUG` level would be particularly useful.

**Comment by tillahoffmann** [comment]
You can set additional environment variables using the `with_env` method of containers. See below for an example.

https://github.com/testcontainers/testcontainers-python/blob/8ca1f917594b81affbb65503b631bea86bd6c13d/tests/test_new_docker_api.py#L17-L19

Feel free to reopen if you have any issues with the snippet.
