### ISSUE TITLE
Is it possible to use a local image?

### ISSUE THREAD

**Issue by awhillas** [testcontainers/testcontainers-python#176]
I'm trying to test an AWS lambda that is defined in a docker image (not s3 zip). I've follow the instruction in [Testing Lambda container images locally](https://docs.aws.amazon.com/lambda/latest/dg/images-test.html) and have a build target that has the entry point. Anyway, I'm trying to run this image, which I have built locally, but using its not getting run?

Code is:
```python
def test_dynamodb():
    # Run the local version on the lambda function
    subject = DockerContainer(image="my-image:latest")
```
running with pytest. Is there something I need to know about running your own containers? (There is no documentation on it as far as I can tell)

**Comment by tillahoffmann** [comment]
You'll have to either use `subject.start()` to start the container or use it as a context manager (recommended).

```python
with DockerContainer(image='mu-image:lastest') as subject:
    # do something with `subject`
```

The advantage of using the context manager is that it will stop and clean up the container for you when the test is over.

**Comment by awhillas** [comment]
Excellent! Thank you. Perhaps this should be added as a note somewhere in the documentation or this query can lay testament to its fact as it stands.

**Comment by awhillas** [comment]
So, i'm trying to run may container at the same time as the localstack container... is this possible? I'm doing this but only ever see localstack spin up?
```
def test_dynamodb():
    # Run the local version on the lambda function
    with DockerContainer(
        image="my-container:latest"
    ) as subject, LocalStackContainer(
        image="localstack/localstack:0.11.4"
    ) as localstack:

        dynamo_endpoint = localstack.get_url()
        dynamo_client = boto3.client("dynamodb", endpoint_url=dynamo_endpoint)
        scan_result = dynamo_client.scan(TableName="foo")
        # Do something with the scan result
```
I can only ever seem to run one container at once? Is this by design?

**Comment by awhillas** [comment]
So, i'm trying to run may container at the same time as the localstack container... is this possible? I'm doing this but only ever see localstack spin up?
```
def test_dynamodb():
    # Run the local version on the lambda function
    with DockerContainer(
        image="my-container:latest"
    ) as subject, LocalStackContainer(
        image="localstack/localstack:0.11.4"
    ) as localstack:

        dynamo_endpoint = localstack.get_url()
        dynamo_client = boto3.client("dynamodb", endpoint_url=dynamo_endpoint)
        scan_result = dynamo_client.scan(TableName="foo")
        # Do something with the scan result
```
I can only seem to run one container at once. Is this by design or should I start looking at docker-compose.yaml files?

**Comment by tillahoffmann** [comment]
I'm closing this for now, but feel free to reopen/comment if you're still having issues with local containers.
