### ISSUE TITLE
Release new version on pypi

### ISSUE THREAD

**Issue by SonoDavid** [testcontainers/testcontainers-python#179]
The latest version which includes eg. rabbitmq support is not yet released in pypi.
The last version released on pipy dates back to 15/08/2021. Please release a newer version with support for some new testcontainers.

**Comment by rkettelerij** [comment]
Any plans for a new release?

**Comment by sealor** [comment]
I would also highly appreciate a new release. The following commit fixes a bug with Docker-In-Docker:
https://github.com/testcontainers/testcontainers-python/commit/cfd6b12511d12d4762ac7f1102075b72b453975a

@tillahoffmann 
Do you have any plans for the next release?

**Comment by tillahoffmann** [comment]
3.5.0 is now released.
