### ISSUE TITLE
Log output on container startup pollutes the test log file

### ISSUE THREAD

**Issue by sealor** [testcontainers/testcontainers-python#192]
I'm using `testcontainers` for Kafka. The Kafka broker needs a few seconds to start-up.
While waiting to be ready the `testcontainers` library logs a great number of unnecessary lines.

Those lines should be reduced to prevent log file pollution.

https://github.com/testcontainers/testcontainers-python/blob/9100aaf8701098db11792fad51116a9c8bf0cfd5/testcontainers/core/waiting_utils.py#L50-L51

Possible solutions are:
- `logger.info('container is not yet ready: %s %s', type(e).__name__, str(e))`
- `logger.info('container is not yet ready: %s', traceback.format_exc(limit=-1))`
- `logger.debug('container is not yet ready: %s', traceback.format_exc())`

What do you think?

**Comment by tillahoffmann** [comment]
Good point. Let's use the `debug` level instead. Are you open to sending a PR?
