### ISSUE TITLE
Use with psycopg3

### ISSUE THREAD

**Issue by Vad1mo** [testcontainers/testcontainers-python#218]
This is more of a question, we are using psycopg3, and I was wondering how I can get this working without writing my onw setup

`sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgresql.psycopg3`

**Comment by tillahoffmann** [comment]
Could you please share a reproducible code snippet, including version numbers of the libraries you're using?

**Comment by Vad1mo** [comment]
just found out psycopg3 is only supported with sqlalchemy 2.
