### ISSUE TITLE
Drop Python 3.6 support

### ISSUE THREAD

**Issue by thedrow** [testcontainers/testcontainers-python#237]
Python 3.6 reached EOL on 23 Dec 2021.
I think we should not maintain support for versions that have reached EOL to ease our maintenance burden.
If a user wants support for Python 3.6, they can use an earlier version of testcontainers until they upgrade.

**Comment by pffijt** [comment]
Python 3.6 support is removed now? I guess this issue can be closed

**Comment by pffijt** [comment]
I created a PR to remove the support of Python 3.6.
