### ISSUE TITLE
Use successor Oracle DB Python driver python-oracledb instead of the old cx-Oracle

### ISSUE THREAD

**Issue by gvenzl** [testcontainers/testcontainers-python#264]
Back in May 2022, Oracle superseded [cx-Oracle](https://pypi.org/project/cx-Oracle/) with [python-oracledb](https://pypi.org/project/oracledb/), see the [release notes](https://python-oracledb.readthedocs.io/en/latest/release_notes.html).

The really nice thing about that is that python-oracledb is not only the successor of cx-Oracle with a better name, but it's also a thin driver, meaning that users no longer have to install any additional binaries or libraries, making it much, much easier for users to just install the driver and connect to an Oracle database.

**Comment by bellaabdelouahab** [comment]
Thank you for the information; it will undoubtedly help the project in deployment.

**Comment by tillahoffmann** [comment]
Thanks for the note. It [looks like](https://levelup.gitconnected.com/using-python-oracledb-1-0-with-sqlalchemy-pandas-django-and-flask-5d84e910cb19) `sqlalchemy` doesn't support `python-oracledb` out of the box yet. But we can switch over once `sqlalchemy` 2.x is released.

**Comment by alexanderankin** [comment]
this has been implemented with the merge of @gvenzl's PR #363
