### ISSUE TITLE
Improve contributing guidelines

### ISSUE THREAD

**Issue by pffijt** [testcontainers/testcontainers-python#269]
The current contributing guidelines describes 3 steps that are quite minimal. We should add additional steps, and maybe we should create a separate contributing.md for better github integration https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors.

**I think the following steps should be atleast added:**

- Class pydoc with usage example with the addition of a new container/module
- Integrate module with sphinx

**Comment by tillahoffmann** [comment]
I've updated the guidelines as part of #290 to address #288. Will close for now, but happy to discuss further changes.
