### ISSUE TITLE
Release new version with Redis

### ISSUE THREAD

**Issue by advance512** [testcontainers/testcontainers-python#27]
I see there are commits for adding support for Redis (and ElasticSearch as well).
https://github.com/testcontainers/testcontainers-python/commit/f6bec8084c8cb0758de0ec4389cca00b30a71b51

When are you going to release a new version to PyPi?

**Comment by tillahoffmann** [comment]
Still need to cut a new release.

**Comment by tillahoffmann** [comment]
Fixed with https://github.com/testcontainers/testcontainers-python/releases/tag/v2.5.
