### ISSUE TITLE
Support more environment variables in PostgreSQL container

### ISSUE THREAD

**Issue by ksquaredkey** [testcontainers/testcontainers-python#278]
With the move from md5 to scram-sha-256 in the PostgreSQL 14.x containers, I find myself needing to set the POSTGRES_HOST_AUTH_METHOD and potentially POSTGRES_INITDB_ARGS.  Seems like it would be good to flesh out the rest of the currently supported environment variables of the official PostgreSQL container.  The ones not yet supported are:

* POSTGRES_INITDB_ARGS
* POSTGRES_INITDB_WALDIR
* POSTGRES_HOST_AUTH_METHOD
* PGDATA

**Comment by santi** [comment]
These environment variables can be set through the `.with_env(<env_var>, <value>)` API on the container itself. Like this:
```python
container = (
    PostgresContainer("postgres:16", driver="pg8000")
    .with_env("POSTGRES_INITDB_ARGS", "args here")
    .with_env("POSTGRES_INITDB_WALDIR", "args here")
)
with container as postgres:
    ...
```

**Comment by ksquaredkey** [comment]
Nice - thanks @santi !  I haven't had the cycles to come back and refactor my original PR but this is a much cleaner, flexible method, so no need.
