### ISSUE TITLE
SqlServerContainer - can't bind port

### ISSUE THREAD

**Issue by spicy-sauce** [testcontainers/testcontainers-python#285]
caused by not having this in the constructor but in the _configure:
`self.with_exposed_ports(self.port_to_expose)`

**Comment by spicy-sauce** [comment]
@tillahoffmann when are you going to release a new version with this fix? is there a plan to release 3.7.2 anytime soon?

**Comment by tillahoffmann** [comment]
Sorry for the slow follow up; should hopefully release a 4.0.0 soon.
