### ISSUE TITLE
Cannot import name 'KeycloakAdmin'

### ISSUE THREAD

**Issue by expploitt** [testcontainers/testcontainers-python#287]
Hi,

I was starting to use testcontainers for mocking a keycloak auth server and I found that the keycloak  API has been changed, so that the line 16 in file keycloak.py

```
from keycloak import KeycloakAdmin
```

should be now

```
from keycloak.keycloak_admin import KeycloakAdmin
```

Thank you!!

**Comment by tillahoffmann** [comment]
Which version of `python-keycloak` are you using? Running `python -c "from keycloak import KeycloakAdmin"` works for me on the most recent version `python-keycloak==2.8.0`.

**Comment by expploitt** [comment]
Sorry for that issue, I was using 2.7.0, now it's working. Closing issue.

Thanks!
