### ISSUE TITLE
Cannot specify custom docker-compose file

### ISSUE THREAD

**Issue by cal97g** [testcontainers/testcontainers-python#29]
If you pass something like `os.path.dirname("{}/docker-compose-test.yml".format(os.getcwd()))` to `testcontainers.compose.DockerCompose` it will try to use `docker-compose.yml` instead of `docker-compose-test.yml`.

I would expect that having being passed a full path to a **file** it would use that specified file.

**Comment by SergeyPirogov** [comment]
@cal97g thank you. Need to fix this

**Comment by pearsonhenri** [comment]
Any word on when this will be published? Would love to pick this up :)
