### ISSUE TITLE
ElasticSearchContainer times out

### ISSUE THREAD

**Issue by Rafaeltheraven** [testcontainers/testcontainers-python#297]
**Describe the bug**

I am trying to use the `ElasticSearchContainer` to write some integration tests, but every time I try to start it, I get a `TimeoutException`. A quick test shows that this does not happen with, for example, the `PostgresContainer`.

**To Reproduce**

```python
>>> from testcontainers.elasticsearch import ElasticSearchContainer
>>> es = ElasticSearchContainer('elasticsearch:8.5.2', port_to_expose=9201)
>>> es.start()
>>> Pulling image elasticsearch:8.5.2
>>> Container started: 4e9a5a27bf64
>>> Waiting to be ready...
>>> Waiting to be ready...
>>> Waiting to be ready...
>>> ...
>>> Traceback (most recent call last):
>>>   File "<stdin>", line 1, in <module>
>>>   File "{my_folder}/.venv/lib/python3.10/site-packages/testcontainers/elasticsearch/__init__.py", line 99, in start
>>>     self._connect()
>>>   File "{my_folder}/.venv/lib/python3.10/site-packages/testcontainers/core/waiting_utils.py", line 55, in wrapper
>>>     raise TimeoutException(
>>> testcontainers.core.exceptions.TimeoutException: Wait time (120s) exceeded for _connect(args: (), kwargs {}). Exception: [Errno 104] Connection reset by peer
```

**Runtime environment**

* python version - 3.10.9
* docker version - 20.10.22
* testcontainers version - 3.7.1
* testcontainers-core version - 0.0.1rc1
* testcontainers-elasticsearch version - 0.0.1rc1
* OS info - `Linux HOSTNAME 6.1.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 07 Jan 2023 15:10:07 +0000 x86_64 GNU/Linux`

**Comment by Rafaeltheraven** [comment]
It seems this was an issue with setting `port_to_expose=9201`. Setting it to anything except for `9200` causes the container to hang. I was under the impression that this would map `9200:9201`, but apparently not. Closing the issue.

**Comment by HansBambel** [comment]
I had the exact same issue. Setting `port_to_expose=9200` fixed it.
