### ISSUE TITLE
Allow configuring the `docker-compose` executable path

### ISSUE THREAD

**Issue by jooola** [testcontainers/testcontainers-python#306]
**Describe the bug**

On newer docker setups, docker-compose is part of docker under a docker sub commands: `docker compose`

This makes this library fail to find `docker-compose` when needed.

For now I have a little script but I expect this library to be able to change the executable name:
```sh
#!/usr/bin/env bash

exec docker compose "$@"
```

**Comment by alexanderankin** [comment]
linking #358
