### ISSUE TITLE
Feature Request:  Localstack container

### ISSUE THREAD

**Issue by sambenas** [testcontainers/testcontainers-python#33]
Localstack is a mock of AWS services.  There is a Localstack available in the testcontainers-java library: https://github.com/testcontainers/testcontainers-java/blob/master/modules/localstack/src/main/java/org/testcontainers/containers/localstack/LocalStackContainer.java

It would be very useful if this were directly available in the python module.  My teams current workaround is to use the DockerCompose object with this docker-compose.yaml file:

```
version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4597:4567-4597"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES="kinesis,lambda"
      - DEBUG=true
      - USE_SSL=true
      - DOCKER_HOST=unix:///var/run/docker.sock
```

**Comment by ImFlog** [comment]
Hello,
I've implemented something without docker compose.
I'm working on polishing the pull request.
