### ISSUE TITLE
`pip install -r requirements/3.x.txt` fails

### ISSUE THREAD

**Issue by pofl** [testcontainers/testcontainers-python#335]
**Describe the bug**

I tried running pip install as per Readme.
I get error
```
Collecting codecov==2.1.12
  ERROR: Could not find a version that satisfies the requirement codecov==2.1.12 (from versions: none)
ERROR: No matching distribution found for codecov==2.1.12
```

Apparently codecov have changed some things around and have taken the codecov package off PyPI completely!
Related: https://github.com/codecov/python-standard/issues/31

**To Reproduce**

Follow readme instructions on a fresh virtualenv

**Runtime environment**

-- should be irrelevant --

**Comment by tillahoffmann** [comment]
Fixed in #332.

**Comment by pofl** [comment]
Oh right yes I noticed this yesterday but only reported today. Apparently you're eliminating bugs quicker than [Lucky Luke his shadow ](https://github.com/testcontainers/testcontainers-python/issues/335)💪

**Comment by tillahoffmann** [comment]
Ha, I wish!
