### ISSUE TITLE
Design question / is a hard dependency on SqlAlchemy really necessary?

### ISSUE THREAD

**Issue by logicbomb** [testcontainers/testcontainers-python#336]
Hi, 

It seems that the `_connect` method is causing the DbContainer project to take a hard dependency on SqlAlchemy.  This is troublesome for those of us not using that package.  Is it meant to do more than verify the database container is up & running? If not, maybe there's a more neutral way of checking like using `pg_isready`?  

https://github.com/testcontainers/testcontainers-python/blob/a2bc91eb5c387d389227117b65e6398e21b5da23/testcontainers/core/generic.py#L31

thanks,
Jason

**Comment by tillahoffmann** [comment]
Yes, that's a good point. We should move away from a hard dependency on sqlalchemy as you suggested. Do you have thoughts on how to integrate that change? A PR would be very welcome!

**Comment by logicbomb** [comment]
i thought to use `popen`  to execute the `pg_isready` command, does that sound like a reasonable approach?

**Comment by HofmeisterAn** [comment]
> i thought to use `popen` to execute the `pg_isready` command, does that sound like a reasonable approach?

Based on my experience maintaining TC for .NET, waiting for `pg_isready` to succeed is not always reliable. There were instances where the .NET Npgsql client could not establish a connection. Since I wait for specific [log messages](https://github.com/testcontainers/testcontainers-dotnet/blob/c983feb779b0115c1c6393b88cfc35b2871306eb/src/Testcontainers.PostgreSql/PostgreSqlBuilder.cs#L131-L137), I have not encountered any connection issues.

**Comment by logicbomb** [comment]
I put together a WIP here: https://github.com/logicbomb/testcontainers-python/pull/1/files

You can see 2 possible implementations, one based on `pg_isready` the other checking logs as described by @HofmeisterAn.   Using `pg_isready` is much less code and seems to work, but I'm happy to go with either.

Also, would you all require a change to the way all databases are verified, or would you accept a change only for Postgres?

**Comment by tillahoffmann** [comment]
You may want to have a look at the `wait_for_logs` function [here](https://github.com/testcontainers/testcontainers-python/blob/35fc2476a5823176d07952f93f8453f20c1e6392/core/testcontainers/core/waiting_utils.py#L79). That should reduce the amount of code required.

**Comment by logicbomb** [comment]
ooh, `wait_for_logs` is nice. i take it you prefer that approach?

**Comment by tillahoffmann** [comment]
Yes, using `wait_for_logs` could be a good option.

**Comment by logicbomb** [comment]
https://github.com/testcontainers/testcontainers-python/pull/340
