### ISSUE TITLE
Port mapping problems when using wormhole pattern

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-python#37]
I've encountered a couple of problems when running in a Docker-in-Docker environment when the using the 'wormhole' pattern. In this context, our test is executed inside a container, and all containers are created as siblings (alongside it). 

The biggest problem is that the port mapping seems to be incorrect - `get_exposed_port` returns the original port when running inside a container:
https://github.com/testcontainers/testcontainers-python/blob/dc956ccd2f7ee80964201eba2f713d6b3379b74c/testcontainers/core/container.py#L89-L93

In testcontainers-java we don't have such a branch and it works well in all contexts I'm aware of. I can't really see the reason for the branch.

I'd be keen to submit a pull request, but want to check whether there's a specific reason for the current code path in case we break a usage I'm not aware of!

**Comment by tuvshuud** [comment]
@rnorth Does #85 address this issue?

**Comment by tillahoffmann** [comment]
@rnorth, closing this issue for now. Feel free to reopen if it continues to be a problem.
