### ISSUE TITLE
get_container_host_ip returning 0.0.0.0 instead of localhost

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-python#38]
When run locally, we're having trouble using `get_container_host_ip`, as it is returning `0.0.0.0`.

https://github.com/testcontainers/testcontainers-python/blob/dc956ccd2f7ee80964201eba2f713d6b3379b74c/testcontainers/core/container.py#L87

As the container IP is intended to be used by clients, surely it should be returning either `localhost` or `127.0.0.1`? I'm not sure about other Python clients, but with asyncio ClientSession we're finding that it is unwilling to accept `0.0.0.0` as a valid server address.

I'd be happy to raise a PR, but again don't want to cause breakage if there's a specific reason for it to be as it is.

**Comment by cal97g** [comment]
@rnorth `0.0.0.0` means it's listening on any possible interface on the local machine iirc - see this: https://serverfault.com/a/78058

If asyncio doesn't like 0.0.0.0, you can use `127.0.0.1` and you'll get the desired effect.

**Comment by rnorth** [comment]
@cal97g that's what I thought; I'm quite used to seeing `0.0.0.0` as a server address but never from the client side.

I think on the basis that `127.0.0.1` is _at least_ as valid an address from a client's perspective, I'd like it if we could contribute a change.

**Comment by cal97g** [comment]
@rnorth I'd suggest just opening a pull request for this and your other issue with a fix. The maintainer doesn't seem to have much free time but tends to be more reactive to PR's in my experience.
