### ISSUE TITLE
Environment variable "testcontainers_host_override" is missing

### ISSUE THREAD

**Issue by meiswjn** [testcontainers/testcontainers-python#383]
**Describe the bug**

In  [Java](https://java.testcontainers.org/features/configuration/#customizing-docker-host-detection) and [Dotnet](https://dotnet.testcontainers.org/custom_configuration/), the variable "TESTCONTAINERS_HOST_OVERRIDE" exists to manually specify the testcontainer host IP. This is required for rootless docker in docker.

**Runtime environment**

RHEL8 with Rootless Docker

**Comment by totallyzen** [comment]
hi @meiswjn thanks for reporting and sorry for the extreme lag on your request!

We're fixing the maintainability of this repo in #405 and tracking the first new release in #418. Please stay tuned and thanks for the issue report!
