### ISSUE TITLE
Overriding entrypoint when starting the (test)container

### ISSUE THREAD

**Issue by jeroenhendricksen** [testcontainers/testcontainers-python#385]
**Describe the "bug"**

I'm trying to create a test-container that starts [mosquitto](https://mosquitto.org/). Because I cannot override the entrypoint at container start time, I cannot properly start mosquitto with a custom configuration, which can only be added tot the container after it has been started, at which time I need the entrypoint not to have started mosquitto (yet).

I would have expected that I could override the entrypoint, like one can do when manually starting a container via docker like this:
`docker run -it --rm --entrypoint='' eclipse-mosquitto /bin/sh`

or like you can do when using testcontainer for .NET as documented [here](https://dotnet.testcontainers.org/api/create_docker_container/#configure-container-start).

It's currently possible to override them command (Cmd), but not the entrypoint...

**Runtime environment**

- I'm running on MacOS 14.0 (23A344) (Sonoma)
- I'm using python version `3.11.5`
- I'm using testcontainers version `3.7.1`
- I'm using docker `24.0.6, build ed223bc` on MacOS using Docker Desktop for Mac

**Questions**

- Is it correct that I have not found a way to override the entrypoint?
- Is there maybe a work-around?
- Why does the .NET version of testcontainers appear to have a way to override the Entrypoint while the python testcontainer version does not? Why is nobody missing it?
- Would you be open for a PR that adds a possibility to allow for overriding the entrypoint, just like you can set (or override) thge Cmd?

**Comment by gudjonragnar** [comment]
I believe you can just set the entrypoint as a part of the keyword arguments passed to the container constructor. Similar to this: https://github.com/testcontainers/testcontainers-python/pull/370/files#diff-22a130a0e2867b808abfa04cb069136d4e0c87e25705dae0342cfbfe6b23c0feR31

**Comment by jeroenhendricksen** [comment]
> I believe you can just set the entrypoint as a part of the keyword arguments passed to the container constructor. Similar to this: https://github.com/testcontainers/testcontainers-python/pull/370/files#diff-22a130a0e2867b808abfa04cb069136d4e0c87e25705dae0342cfbfe6b23c0feR31

Thank you, that seems to work!
