### ISSUE TITLE
[question] Provide parameters for docker run

### ISSUE THREAD

**Issue by nicopaez** [testcontainers/testcontainers-python#387]
Hi, I need to pass "--privileged --security-opt="seccomp=unconfined"" to docker run, I mean: the command I need to execute is:

```bash
docker run --privileged --security-opt="seccomp=unconfined" qdrant/qdrant:v1.6.0
```

Is it possible?

**Comment by Mohsin-Ul-Islam** [comment]
Hi @nicopaez 

Have you tried this:

```python
with DockerContainer('qdrant/qdrant:v1.6.0', priviliged=true, security_opt=['seccomp=unconfined']) as container:
  pass
```

These options are supported via `**kwargs` when creating and running your container.

See: https://github.com/docker/docker-py/blob/e9d4ddfaece229fbd2df1a1bfa3f4f513f33d1ac/docker/models/containers.py#L735

And also: https://github.com/docker/docker-py/blob/e9d4ddfaece229fbd2df1a1bfa3f4f513f33d1ac/docker/models/containers.py#L718

**Comment by kiview** [comment]
I'll close this, since I assume the instructions provided by @Mohsin-Ul-Islam should solve this use case. Please let us know if this does not work for you @nicopaez.
