### ISSUE TITLE
Make minio pip-installable as an extra

### ISSUE THREAD

**Issue by dsgibbons** [testcontainers/testcontainers-python#390]
**Describe the bug**

`testcontainers.minio` must be installed via the command `pip install testcontainers-minio`. I'd expect this to be pip installable as an extra: `pip install testcontainers[minio]`

**To Reproduce**

```
pip install testcontainers[minio]

WARNING: testcontainers 3.7.1 does not provide the extra 'minio'
```

**Comment by totallyzen** [comment]
hi @dsgibbons ! please see #408 for the [fix](https://github.com/testcontainers/testcontainers-python/pull/408/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R97) and #418 for when we'll try to release the fixes :pray:
