### ISSUE TITLE
'DockerContainer' object has no attribute '_container'

### ISSUE THREAD

**Issue by theopfr** [testcontainers/testcontainers-python#399]
**Creating Postgres Container instance results in error: 'PostgresContainer' object has no attribute '_container'**

I tried starting a Postgres container and got the following error:
```
Exception ignored in: <function DockerContainer.__del__ at 0x7f1da5122b80>
Traceback (most recent call last):
  File "/.venv/lib/python3.9/site-packages/testcontainers/core/container.py", line 80, in __del__
AttributeError: 'PostgresContainer' object has no attribute '_container'
```
I already saw an issue [#353](https://github.com/testcontainers/testcontainers-python/issues/353) which was about the same error but it seems to persist.
See the code I used below.

**To Reproduce**

```python
from testcontainers.postgres import PostgresContainer

def get_postgres_uri():
    # Use a PostgreSQL Docker container for testing
    with PostgresContainer("postgres:latest") as postgres:
        return postgres.get_connection_url()
```
I also tried out the code in the [postgres/tests/test_postgres.py](https://github.com/testcontainers/testcontainers-python/blob/main/postgres/tests/test_postgres.py) file and it failed with the same error message.

**Runtime environment**

OS: Pop!_OS 22.04 LTS x86_64
Python version: Python 3.9.12
Docker version: 24.0.5
testcontainers version: 3.7.1

**Comment by alexanderankin** [comment]
im trying and failing to reproduce (on ubuntu) with:

```shell
uname -a # Linux z14-1 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
python -V # Python 3.9.18
mkdir testcontainers-python-issues-399 && cd $_
python -m venv .venv && . .venv/bin/activate
cat > test.py <<EOF
from testcontainers.postgres import PostgresContainer

def get_postgres_uri():
    # Use a PostgreSQL Docker container for testing
    with PostgresContainer("postgres:16-alpine") as postgres:
        return postgres.get_connection_url()


print(get_postgres_uri())
EOF
python test.py
```
and i get these logs:
```console
$ python test.py 
Pulling image postgres:16-alpine
Container started: 84479badddc7
Waiting to be ready...
Waiting to be ready...
Waiting to be ready...
Waiting to be ready...
Waiting to be ready...
postgresql+psycopg2://test:test@localhost:32769/test
```

docker version is also 24:

```console
$ docker -v
Docker version 24.0.7, build afdd53b
```

i dont think this means there isn't an issue - maybe spending some time staring at the code of the library will show some obvious codepaths which cause the issue

**Comment by danb27** [comment]
Same issue!

**Comment by totallyzen** [comment]
heyo, I think this isn't OS dependent, but makes for some flaky testing
I bumped into this right here on our CI.

So I think this is defo a bug related to failing to create the container
See an example run
https://github.com/testcontainers/testcontainers-python/actions/runs/7889768439/job/21530402642

**Comment by totallyzen** [comment]
In fact I'm getting more convinced this issue is present when we encounter issues with the docker client. Some refactoring and defensive coding is needed as it seems.
