### ISSUE TITLE
PubSub on PyPI is out of sync with this repo

### ISSUE THREAD

**Issue by barendatnicolab** [testcontainers/testcontainers-python#403]
**Describe the bug**

If one is to download `testcontainers-gcp` from PyPI, you are getting an outdated version, one that doesn't match with current `main`.

```
>>> pip download testcontainers-gcp
...
>>> ls
google_cloud_pubsub-1.7.2-py2.py3-none-any.whl		
testcontainers_gcp-0.0.1rc1-py3-none-any.whl
... (and many more)
``` 

However, current `setup.py` also mentions the same version (`0.0.1rc1` that is) [here](https://github.com/testcontainers/testcontainers-python/blob/main/google/setup.py). That updated `setup.py` sets a requirement on `pubsub>=2`. As you can see above, it actually downloads pubsub 1.7.2.
I reckon the current PyPI version is based on code before this commit: https://github.com/testcontainers/testcontainers-python/commit/934c8d884ff513d3ede3b7faab2860f110799585

**To Reproduce**

```
pip download testcontainers-gcp
```

**Runtime environment**

Running with 
python=3.9.18
pip==23.0.1

**To solve (suggestion)**
Publish a new version that reflects latest state of `main`.

p.s. thanks for the maintainers for all the work you've done on this repo <3

**Comment by totallyzen** [comment]
hey @barendatnicolab going forward we are only releasing one package with python's `extras` style - so in effect we'll release all the unreleased stuff in one go and tracking that under #418.

Please follow that issue if you want to ask more questions or know when to receive some updates!
