### ISSUE TITLE
Custom registry

### ISSUE THREAD

**Issue by marintrooper23** [testcontainers/testcontainers-python#414]
More likely not a bug, but a question. How to teach tescontainers to take images from a private registry? Let's say from artifactory

**Comment by totallyzen** [comment]
hey @marintrooper23 sorry for the delay (I'm still not used to regular scanning of the issues on tc-python :innocent: )

The documentation of the base container image could be improved for sure, however there is an `image: str` as the first parameter [here](https://github.com/testcontainers/testcontainers-python/blob/main/core/testcontainers/core/container.py#L25-L34)

This follows standard docker practices with being a fully qualified docker image name.
The general format is `<registry>/<image-name>:<image-tag>`

If you do `docker pull hello-world` then docker will tell you the full image URL it just pulled:
```shell
$ docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
Digest: sha256:4bd78111b6914a99dbc560e6a20eab57ff6655aea4a80c50b0c5491968cbc2e6
Status: Image is up to date for hello-world:latest
docker.io/library/hello-world:latest
```

What this should teach you is that:
- The default for image-tag is `latest` - this works with all registires!
- The default for registry is `docker.io/library` - this follows standard url practices. 
  - For example, AWS ECR has it's own mirror of this lib `public.ecr.aws/docker/library/hello-world:latest`

**Comment by alexanderankin** [comment]
Most testcontainers take an image config as the first argument, e.g. `DockerContainer("images.mycompany.net:5000/public-images/postgres:14-company-internal-version")` vs `DockerContainer("postgres:14")`
