### ISSUE TITLE
Are there plans to support python Flask servers? 

### ISSUE THREAD

**Issue by davehouser1** [testcontainers/testcontainers-python#416]
Not really a bug but wondering if Flask will be supported? We need a system that can deploy Flask containers configured as we decide and test with the API for each one. 
If I should put this somewhere else me know.

**Comment by alexanderankin** [comment]
how do you have your flask apps structured, like adjacent folders?

```
./apps/app1/pyproject.toml, ./apps/app1/app1/main.py
./apps/app2/pyproject.toml, ./apps/app2/app2/main.py
```

and then you want an integration test to live in `./apps/itest/e2e-{auth,apples,oranges}.py`?

**Comment by davehouser1** [comment]
Actually we call instances of classes that build out a Flask app with specific responses and then start it with custom method that uses `gevent()`
So right now I have a bunch of classes I call to build each flask app. 
We do this to perform auto testing, to make sure API calls come back the way we want in simple high level tests. 
Curious if it would be easier to call `testcontainers` instead and just have it use my modules, to stand up containers instead of gevent instances.

**Comment by alexanderankin** [comment]
hm, you can certainly containerize a python app arbitrarily with bind mounts, consider this java example - [this app](https://github.com/alexanderankin/side-projects/tree/main/cloud/util/logging-proxy/spring-boot-netty) starts [this other app](https://github.com/alexanderankin/side-projects/tree/main/cloud/util/logging-proxy/logged-application) as a containerized dependency. I simply pass the path to the jar (in this case would be `app.py` or the python file to run) [here](https://github.com/alexanderankin/side-projects/blob/c48ee81a50902135902f75d1007c4326aceb3d96/cloud/util/logging-proxy/spring-boot-netty/build.gradle#L30) and launch by spinning up a generic java image, with my jar file copied into it [here](https://github.com/alexanderankin/side-projects/blob/c48ee81a50902135902f75d1007c4326aceb3d96/cloud/util/logging-proxy/spring-boot-netty/src/itest/java/org/cloud/logging/proxy/sb/netty/AsyncLoggingProxyAppITest.java#L36-L42)

if this is more or less the pattern i can try to replicate in python, should be totally possible. not sure if it is what you are trying to achieve

**Comment by totallyzen** [comment]
Hi @davehouser1!

Sorry for the delays, if I understand correctly you are asking for a generic Flask container that can mount your app and run it.
However, any additional dependencies the app needs to function correctly becomes an inherent dependency!

Therefore it's far better to build your own container use it. 
There are some examples around in the repo on how to wait for healthy URLs.

Sorry for the delay on an answer, I hope this helps!
