### ISSUE TITLE
New release planned: 4.0.0

### ISSUE THREAD

**Issue by CarliJoy** [testcontainers/testcontainers-python#418]
The last release is almost two years old.

Is a new release planned?

**Comment by alexanderankin** [comment]
If this is just asking when it will happen, we are working on it in #405 , #408

**Comment by CarliJoy** [comment]
Thank you for your efforts in creating/maintaing this project!
The link to the issue is enough for me.
I would suggest to leave this "issue" open as long there is no new release so people with the same question can be pointed to the correct "blocking issues".

**Comment by totallyzen** [comment]
@CarliJoy hey! In fact I pinned your issue so folks can see. :slightly_smiling_face: Thanks for the interest in the project!

Once we're out of the woods with building and testing (see #408) the pace of changes should pick up a bit.

**Comment by alexanderankin** [comment]
hopefully we can get linting in here and docker compose either the old one or the new one (#400 (#362) or #426) - and we can do things like fixing the situation with reaper (#314) for 4.1 - also fairly high on my list is in general waiting strategies and in particular the vast array of dependencies for things like postgres that not everyone needs (todo find this one but its fairly obvious what to do - copy tc-java's way - waiting for logs most of the time) - not sure if im missing anything

**Comment by totallyzen** [comment]
hey, so I've got a working PR that I have confidence in -> #429 

Release please can still be instructed manually to create new release PRs (via local CLI calls that create release them) for the usage of release-candidates, but it also should improve future release stability by not requiring individuals to release.

**Comment by totallyzen** [comment]
we have a release PR, but we don't have all the changes needed yet.
release PR -> #433 -> will update to 4.0 once we have #426 merged

**Comment by totallyzen** [comment]
https://pypi.org/project/testcontainers/4.0.0/
