### ISSUE TITLE
More options for consuming DSN?

### ISSUE THREAD

**Issue by DarrienG** [testcontainers/testcontainers-python#42]
For god only knows what reason, some older mysql libraries (e.g. MySQLdb: http://mysql-python.sourceforge.net/MySQLdb.html) don't accept a full DSN and only a parameterized DSN.

e.g. 
```python
conn = MySQLdb.connect(
    database.get_connection()                                                                                                                                    
)                                                                                                                                                                
```
Is illegal.

What it really wants is:
```python
db=MySQLdb.connect(host="localhost",user="joebob",
                  passwd="moonpie",db="thangs",port=50505)
```

But the only parameters available right now are:
```
MYSQL_DATABASE
MYSQL_PASSWORD
MYSQL_ROOT_PASSWORD
MYSQL_USER
```

I think to flesh out what's missing, what should also be added is:
```
MYSQL_HOST
MYSQL_PORT
```

There may be more, but I think that's more than enough to satisfy most needs of MySQLdb.

**Comment by kennedy** [comment]
you can prob experiment by seeing if `database.get_container_host_ip()` would provide the host, and `database.get_exposed_port()` for the port

**Comment by tillahoffmann** [comment]
The option @kennedy suggests is indeed what is used by `get_connection_url` internally. See below. https://github.com/testcontainers/testcontainers-python/blob/c081c1899dea85a221c27bc849d2ad7abfb4079e/testcontainers/core/generic.py#L35-L44
