### ISSUE TITLE
Question: Contribution + Tooling

### ISSUE THREAD

**Issue by bearrito** [testcontainers/testcontainers-python#430]
I am attempting to setup this project so I can contribute back a feature.

Running into an issue with setup.

The docs indicate to use the requirements file. https://testcontainers-python.readthedocs.io/en/latest/README.html#development-and-contributing. I don't think there are requirements files in the project anymore.

I'm a VSCode user and I see the `.devcontainers`. However that is unhappy as well. 
 ```
Running the postCreateCommand from devcontainer.json...

[26177 ms] Start: Run in container: /bin/sh -c pip install --user -r requirements/ubuntu-latest-3.11.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements/ubuntu-latest-3.11.txt'
[26741 ms] postCreateCommand failed with exit code 1. Skipping any further user-provided commands.
Done. Press any key to close the terminal.
```

I can see the issues related to switching over to poetry. 
It looks likes the docs were updated in src but not on the website?
https://github.com/testcontainers/testcontainers-python/commit/098db159cbdb54442465f8f6060bbb264f10de46#diff-8a92b9b831adb807d36f1fc8109f18252b1a8d87713196370cdb297d1dc44889R84

Since this doens't work for me I cannot test, but poetry and devcontainers typically don't work together well without a bit of coaxing. Will devcontainers continue to be supported?

Is the repo and flux and should I just wait a few weeks for PR's to settle?

**Comment by alexanderankin** [comment]
Poetry is stable, next stuff before 4.0 is compose and maybe release
automation. Probably after that is whatever is being discussed in the
pinned issues.

**Comment by bearrito** [comment]
So the docs are just out of date, and devcontainers are up in the air?

**Comment by alexanderankin** [comment]
Should be as simple as poetry install --all-extras

**Comment by bearrito** [comment]
Noted. Good enough.
