### ISSUE TITLE
reuse/singleton containers

### ISSUE THREAD

**Issue by kennedy** [testcontainers/testcontainers-python#53]
Hello,
I was looking at testcontainers-java and they implemented a way to "reuse" containers. 

Is there away to do that in testcontainer-python?

**Comment by tillahoffmann** [comment]
Reusing containers largely depends on how you manage the lifecycle of the container. If you are using pytest, the following is a working example. The `container` function defines a fixture (see [here](https://docs.pytest.org/en/latest/fixture.html) for details) with a specific scope which defines how the lifecycle of the fixture is managed. Find out more [here](https://docs.pytest.org/en/latest/fixture.html#scope-sharing-a-fixture-instance-across-tests-in-a-class-module-or-session). In short, possible fixture values are

* `function`: a new container for each separate test
* `class`: a new container for each test class (if you structure your tests in classes)
* `module`: a new container for each `.py` file
* `session`: a new container for each test session. In other words, a singleton.

```python
# test_lifecycle.py
import os
import pytest
from testcontainers.core.container import DockerContainer


@pytest.fixture(scope=os.environ['SCOPE'])
def container():
    with DockerContainer("hello-world") as c:
        yield c


@pytest.mark.parametrize('arg', range(2))
def test_something(arg, container):
    print("testing %d with %s" % (arg, container))
```

Running the tests with different values of the `SCOPE` environment variable gives the following results.

```
$ SCOPE=function pytest -sv test_lifecycle.py

============================= test session starts ==============================
platform darwin -- Python 3.7.6, pytest-5.3.2, py-1.8.1, pluggy-0.13.1 -- /Users/till/.pyenv/versions/3.7.6/envs/testcontainers/bin/python
cachedir: .pytest_cache
rootdir: /Users/till/git/testcontainers-python
collecting ... collected 2 items

test_lifecycle.py::test_something[0] 
Pulling image hello-world

Container started:  c97a386e4f
testing 0 with <testcontainers.core.container.DockerContainer object at 0x10b9156d0>
PASSED
test_lifecycle.py::test_something[1] 
Pulling image hello-world

Container started:  00701934a5
testing 1 with <testcontainers.core.container.DockerContainer object at 0x10b95ac10>
PASSED

============================== 2 passed in 3.65s ===============================
```

Note that the two container objects are different: `<... at 0x10b9156d0>` vs `<... at 0x10b95ac10>`.

```
$ SCOPE=session pytest -sv test_lifecycle.py

============================= test session starts ==============================
platform darwin -- Python 3.7.6, pytest-5.3.2, py-1.8.1, pluggy-0.13.1 -- /Users/till/.pyenv/versions/3.7.6/envs/testcontainers/bin/python
cachedir: .pytest_cache
rootdir: /Users/till/git/testcontainers-python
collecting ... collected 2 items

test_lifecycle.py::test_something[0] 
Pulling image hello-world

Container started:  022014e4f4
testing 0 with <testcontainers.core.container.DockerContainer object at 0x10ad547d0>
PASSED
test_lifecycle.py::test_something[1] testing 1 with <testcontainers.core.container.DockerContainer object at 0x10ad547d0>
PASSED

============================== 2 passed in 1.23s ===============================
```

Note that the same container object is used: `<... at 0x10ad547d0>`.

Does that help?
