### ISSUE TITLE
Adding PostgreSQL extensions?

### ISSUE THREAD

**Issue by ict4eo** [testcontainers/testcontainers-python#54]
Is it possible for the test-container to be configured to allow for extensions?  For example, PostGIS (https://postgis.net/install/) is a widely used one.

**Comment by tillahoffmann** [comment]
A few options:

* You can build your own docker image based on the official postgres images (search for "Additional Extensions" [here](https://hub.docker.com/_/postgres)).
* You can use pre-built images that include the extension (google "docker postgres postgis" or see [here](https://hub.docker.com/r/mdillon/postgis) for an example).
* You can install the extensions when you spin up the container (but that will likely take a significant amount of time).
