### ISSUE TITLE
PyPI release candidate clarification

### ISSUE THREAD

**Issue by kevin-lithic** [testcontainers/testcontainers-python#540]
**Describe the bug**

The latest version of testcontainers does not work with the release candidate version in PyPi. The issue being that there is a deprecated db_name field being used. After looking at the code it looks like the latest version in this repo doesnt reference that and should work. Can you release a new version of the code to PyPi?

**Comment by alexanderankin** [comment]
release candidates don't have any guarantees according to the semantic versioning specification (https://stackoverflow.com/a/50983511), so i would not use them if i were you. can you specify exactly what you are seeing, or which rc candidate you are referring to, to ensure that no code got lost in the process? technically speaking releases are automated in this repo so its not possible for PyPI to be "out of date" (but rc candidates are quite random so i can review for you)

**Comment by alexanderankin** [comment]
closing for now but feel free to respond if any further clarification needed.
