### ISSUE TITLE
v2.5 installed from PyPI does not have mongodb module

### ISSUE THREAD

**Issue by dsabsay** [testcontainers/testcontainers-python#60]
I've installed v2.5 via `pip`. Attempting to use the `mongodb` module like so:
```
from testcontainers.mongodb import MongoDbContainer
```
gives me:
```
ImportError: No module named mongodb
```
Looking in my virtual environment:
```
(env) sabsays-MacBook-Pro:st2-test-utils sabsay$ ls env/lib/python2.7/site-packages/testcontainers/
__init__.py       compose.pyc       elasticsearch.pyc google            nginx.py          oracle.pyc        redis.py
__init__.pyc      core              general.py        mysql.py          nginx.pyc         postgres.py       redis.pyc
compose.py        elasticsearch.py  general.pyc       mysql.pyc         oracle.py         postgres.pyc      selenium.py
```
it is indeed not there :-)

**Comment by dsabsay** [comment]
Oops, hehe. Forgot about the options to install with `pip install testcontainers[mongodb]`.

That seems to work although, `core/generic.py` imports sqlalchemy which shouldn't be needed to use mongodb. Think the `DbContainer` class in core/generic.py really doesn't belong there, as it brings in extra (optional) dependencies.

**Comment by vinjana** [comment]
I still have to use

```bash
pip install git+https://github.com/testcontainers/testcontainers-python.git` 
```

to get a working testcontainers[mongodb] in Gitlab-CI.

**Comment by tillahoffmann** [comment]
The extra is called `mongo` rather than `mongodb`. Version 2.6.0 should have that included.
