### ISSUE TITLE
Bug: DockerImage (image.py) is missing or documentation not up to date.

### ISSUE THREAD

**Issue by richard-infai** [testcontainers/testcontainers-python#609]
**Describe the bug**

In the readme on https://github.com/testcontainers/testcontainers-python/blob/main/core/README.rst the documention citates there should be a `DockerImage` with `from testcontainers.core.image import DockerImage`. But it is missing for me in the package.

If i install the current version with poetry file is missing.
Also downloaded from https://pypi.org/project/testcontainers/4.5.1/#files and looked in the gz file. The file is missing, too.

My Download path is https://files.pythonhosted.org/packages/ac/61/1057fa25b341e97e45a47f71aad08f7ab82beaeed51c3014932627d3ec54/testcontainers-4.5.1.tar.gz

The file is in this repository but not in the final build (it seems). Is the documentation up to date?

**To Reproduce**

Download current package and look for the file

**Runtime environment**

- win 10
- python 3.10
- Poetry 1.8.3

**Comment by alexanderankin** [comment]
my apologies, i must have merged the docs before the actual feature, will be resolved with next release.

**Comment by black-snow** [comment]
When will the next release land? I was puzzled by this as well. Coming from JVM world I was confused not to find a way to build an image.
