### ISSUE TITLE
Bug: port mapping not working with `with_network` (with_exposed_ports)

### ISSUE THREAD

**Issue by fabricebaranski** [testcontainers/testcontainers-python#645]
Hi all,
I would like to have two containers connected each others, with a code similar to
```
test_network = Network()
test_network.create()
container1 = DockerContainer("myimage1", hostname="myimage1") \
        .with_network(test_network).with_network_aliases("myalias1").with_exposed_ports(9098)
container2 = DockerContainer("myimage1", hostname="myimage2") \
        .with_network(test_network).with_network_aliases("myalias2").with_exposed_ports(9099)
container1.start()
container2.start()
```
I regularly have no port mapping for my containers. Do you have any ideas?

**Comment by fabricebaranski** [comment]
Moreover, I have some difficulties to create communication between these two containers on gitlab ci.

**Comment by mgorsk1** [comment]
I also experience some difficulties with advanced network setup and I came to the conclusion it's due to the way it's implemented in TC:
- when new container is created, `self._container = docker_client.run(` is executed without `network` kwarg, this means container has default network assigned by default:
```
        if "network" not in kwargs and not get_docker_host():
            # Otherwise we'll try to find the docker host for dind usage.
            host_network = self.find_host_network()
            if host_network:
                kwargs["network"] = host_network
```
- later, if self._network is not empty (after adding `.with_network` to container definition), container is connected to it (so it now is connected to two networks):
```
        if self._network:
            self._network.connect(self._container.id, self._network_aliases)
```

the solution could be to pass `network` kwarg to container constructor and omit `.with_network` completely but then we cannot assign network aliases.

**Comment by fabricebaranski** [comment]
It seems to work when I add .`with_bind_ports(9099, 0)`

**Comment by champialex** [comment]
Confirming this does not work, for good reasons:

When calling `docker_client.run` in container.py#start, it doesn't pass the network through.
If you look at h[ow the method behaves](https://github.com/testcontainers/testcontainers-python/blob/1e439232e35ce0091f20993273e1f01d8c0119c4/core/testcontainers/core/docker_client.py#L92), it will then resort to host networking [which is not meant to support port bindings. ](https://docs.docker.com/network/drivers/host/): if you run `docker port` on the created container, no port will show up.
By the time the network is connected ([L102](https://github.com/testcontainers/testcontainers-python/blob/1e439232e35ce0091f20993273e1f01d8c0119c4/core/testcontainers/core/container.py#L102)), it is too late. 

Instead, this is what start should look like:

```py
....
        self._container = docker_client.run(
            self.image,
            command=self._command,
            detach=True,
            environment=self.env,
            ports=self.ports,
            name=self._name,
            volumes=self.volumes,
            # New params
            network=network.name, 
            networking_config={network.name: EndpointConfig(version, aliases=[self._network_alias], **self._network_endpoint_config) )
            **self._kwargs,
        )
```

In the meantime a workaround is:


```py
    # replace:
    # ctr.with_network(network)
    # ctr.with_network_aliases("network_alias")
   # with:
    ctr.with_kwargs(
        network=network.name, networking_config={network.name: EndpointConfig("1.33", aliases=["network_alias"])}
    )
```

**Comment by Lenormju** [comment]
I struggled for hours with the same problem, and got this to work (in Pytest's fixtures) :

```python
MQTT_BROKER_NETWORK_ALIAS = "mqtt_broker"

@pytest.fixture()
def network_for_test() -> Generator[Network, None, None]:
    test_network = Network()
    with test_network:
        yield test_network


@pytest.fixture()
def mqtt_broker(network_for_test: Network) -> Generator[MosquittoContainer, None, None]:
    mqtt_broker = MosquittoContainer() \
        .with_network(network_for_test) \
        .with_network_aliases(MQTT_BROKER_NETWORK_ALIAS)
    with mqtt_broker:
        yield mqtt_broker


@pytest.fixture()
def web_server(mqtt_broker: MosquittoContainer,
               network_for_test: Network) -> Generator[ServerContainer, None, None]:
    # [...]
    web_server = ServerContainer(
        image="something", port=80
    ).with_network(network_for_test)
    # [...]
    with web_server:
        yield web_server
```
This way, I can make the web server connect to the MQTT broker (using the `MQTT_BROKER_NETWORK_ALIAS`).

**Comment by mgorsk1** [comment]
I've combined @champialex and mine findings into https://github.com/testcontainers/testcontainers-python/pull/678
