### ISSUE TITLE
Question:  where to add the Chrome options for BrowserWebDriverContainer

### ISSUE THREAD

**Issue by stevechow21** [testcontainers/testcontainers-python#652]
## What are you trying to do?

start the Chrome with options, such as ('--disable-dev-shm-usage')

## Where are you trying to do it?

add argument

## Runtime environment

i want to add chrome options, but i don't know where to add the options, below scripts i added options in the method BrowserWebDriverContainer, it seems no work

```bash
        options = Options()
        options.add_argument('--disable-dev-shm-usage')
        options.add_argument('--headless')
        dr = BrowserWebDriverContainer(capabilities=DesiredCapabilities.CHROME, options=options)
        dr.start()
        driver = dr.get_driver()
        driver.maximize_window()
```

**Comment by alexanderankin** [comment]
does https://github.com/testcontainers/testcontainers-python/pull/654 work for this?

**Comment by stevechow21** [comment]
it works, thanks a lot
