### ISSUE TITLE
Bug: MSSQL Cannot run 'SELECT 1': container is not ready

### ISSUE THREAD

**Issue by grieve54706** [testcontainers/testcontainers-python#666]
**Describe the bug**

Microsoft changes the `mssql-tools` folder name to `mssql-tools18` at `2019-latest` and `2022-latest`. Testcontainer could not use the right path to check database status by mssql tool.

https://github.com/testcontainers/testcontainers-python/blob/e1e3d13b47923dd7124196e6b743799bd87b6885/modules/mssql/testcontainers/mssql/__init__.py#L55

Relate https://github.com/microsoft/mssql-docker/issues/892#issuecomment-2249029917

**To Reproduce**

```python
from testcontainers.mssql import SqlServerContainer

mssql = SqlServerContainer("mcr.microsoft.com/mssql/server:2019-latest").start()
```

**Solution**
We need to determine the exact location of the MSSQL tool before utilizing it.

**Comment by kiview** [comment]
This issue is also present in other Testcontainers implementations: https://github.com/testcontainers/testcontainers-dotnet/issues/1220

**Comment by alexanderankin** [comment]
ok so based on the quoting this is being executed by the container's shell. so it can simply be replaced with `$(which sqlcmd)` except that it may not be in the PATH:

```console
$ docker image inspect mcr.microsoft.com/mssql/server:2019-latest | jq .[].Config.Env
[
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
]
```

so how should we fix?

```
/opt/mssql-tools*/bin/sqlcmd
```

this does appear to work:

```console
$ docker run --rm -it --entrypoint 'bash' mcr.microsoft.com/mssql/server:2019-latest
mssql@5d2990b93a8a:/$ file /opt/mssql-tools*/bin/sqlcmd
/opt/mssql-tools18/bin/sqlcmd: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=a341d98e7522c347f723c8f11a1170d9cdf8ad7a, stripped
mssql@5d2990b93a8a:/$ /opt/mssql-tools*/bin/sqlcmd



^CCanceling connection...
mssql@5d2990b93a8a:/$
```

**Comment by grieve54706** [comment]
> so how should we fix?
> 
> ```
> /opt/mssql-tools*/bin/sqlcmd
> ```
> 
> this does appear to work:
> 
> ```
> $ docker run --rm -it --entrypoint 'bash' mcr.microsoft.com/mssql/server:2019-latest
> mssql@5d2990b93a8a:/$ file /opt/mssql-tools*/bin/sqlcmd
> /opt/mssql-tools18/bin/sqlcmd: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=a341d98e7522c347f723c8f11a1170d9cdf8ad7a, stripped
> mssql@5d2990b93a8a:/$ /opt/mssql-tools*/bin/sqlcmd
> 
> 
> 
> ^CCanceling connection...
> mssql@5d2990b93a8a:/$
> ```

Cool. This is an elegant solution.

**Comment by grieve54706** [comment]
Hi @alexanderankin, unfortunately, docker execute run `/opt/mssql-tools*/bin/sqlcmd` will get error
```
b'OCI runtime exec failed: exec failed: unable to start container process: exec: "/opt/mssql-tools*/bin/sqlcmd": stat /opt/mssql-tools*/bin/sqlcmd: no such file or directory: unknown\r\n'
```
