### ISSUE TITLE
Bug: hardcoded dialect/driver parameter in connection url in mysql container

### ISSUE THREAD

**Issue by nightblure** [testcontainers/testcontainers-python#727]
**Describe the bug**

I find it strange that the dialect or driver parameter is hardcoded here (look screenshot below), because today there are [many different methods and drivers for connecting to mysql](https://docs.sqlalchemy.org/en/20/dialects/mysql.html#module-sqlalchemy.dialects.mysql.mariadbconnector). If I use something other than pymysql, I get the wrong connection address from the `get_connection_url` method.

Code:
![Image](https://github.com/user-attachments/assets/1d554724-da72-4024-b9e1-075e3cde644a)

**Possible solution**
1. Remove this hardcoded line and leave only `mysql://...`;
2. Allow you to pass an optional dialect or driver parameter to the `get_connection_url` function or the `MySqlContainer` class initializer. If its value is non-empty, then in the `get_connection_url` method it will be inserted into the right place in the connection string

---

**To Reproduce**

- just see to current code (testcontainers 4.8.2)

**Runtime environment**
Looks optional for this issue

**Comment by nightblure** [comment]
If this solution works, I could do it

**Comment by totallyzen** [comment]
Please feel free to contribute!

I would recommend putting the dialect in the constructor, not `self.get_connection_url()` - it's where the other settings go as well by the looks of it.
