### ISSUE TITLE
Bug: MinioContainer module not found

### ISSUE THREAD

**Issue by nilskre** [testcontainers/testcontainers-python#752]
**MinioContainer module not found**

When running the code for the Minio container [https://testcontainers-python.readthedocs.io/en/latest/modules/minio/README.html#testcontainers.minio.MinioContainer](https://testcontainers-python.readthedocs.io/en/latest/modules/minio/README.html#testcontainers.minio.MinioContainer) with the latest testcontainers-python version `v4.9.0` there is an error `ModuleNotFoundError: No module named 'minio'`. Other containers like postregsql are working.

**To Reproduce**

Provide a self-contained code snippet that illustrates the bug or unexpected behavior. Ideally, send a Pull Request to illustrate with a test that illustrates the problem.

```python
from testcontainers.minio import MinioContainer
```

raises `ModuleNotFoundError: No module named 'minio'`

**Runtime environment**

- Ubuntu 24.04 
- with a Python project using poetry for managing dependencies
- `testcontainers = "^4.9.0"`
- Python `v3.12.3`
- Docker `Docker version 27.3.1, build ce12230`

What do I need to change to make this work?
Thanks in advance for any help!

**Comment by alexanderankin** [comment]
have you installed with `testcontainers[minio]`? this installs dependencies like minio library for minio container. wouldn't make sense to install sqlalchemy for users of miniocontainer, or minio for postgresql users. postgresql just so happens to not require any other dependencies, so works even if you disregard the "extra" (`[minio]`)

**Comment by nilskre** [comment]
Thanks a lot for your fast and helpful reply! That was exactly my fault. I have just installed `testcontainers` without the `[minio]` specification.
