### ISSUE TITLE
Dev environment setup

### ISSUE THREAD

**Issue by jtanios** [testcontainers/testcontainers-python#77]
Some documentation on setting up the dev environment would be great. 

Also, why not use a dependency management package like `pipenv` or `poetry`?

**Comment by tillahoffmann** [comment]
Yes, good point, we should add some information on how to set up a dev environment. 

Re dependency management, we use [`pip-tools`](https://github.com/jazzband/pip-tools) because `pipenv` is not yet as stable as we'd like.
